version: 2

sources:
  - name: "{{ var('source_name') }}"
    database: "{{ var('input_database') }}"
    schema:  "{{ var('input_schema') }}"
    tables:
      - name: medical_claim
        identifier: tuva_input_claims
      - name: eligibility
        identifier: tuva_input_eligibility
